"""v6 graph sync runs

Revision ID: 13f7948e8cf3
Revises: fe7e6ae943d8
Create Date: 2026-09-23 13:45:06.218755
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '13f7948e8cf3'
down_revision: str | None = 'fe7e6ae943d8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('backend', sa.String(length=16), nullable=False),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('node_counts', sa.JSON(), nullable=True),
    sa.Column('edge_counts', sa.JSON(), nullable=True),
    sa.Column('graph_node_counts', sa.JSON(), nullable=True),
    sa.Column('graph_edge_counts', sa.JSON(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('removed_nodes', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_graph_sync_runs_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_graph_sync_runs_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_graph_sync_runs'))
    )
    op.create_index(op.f('ix_graph_sync_runs_hospital_id'), 'graph_sync_runs', ['hospital_id'], unique=False)
    op.create_index('ix_graph_sync_runs_hospital_started', 'graph_sync_runs', ['hospital_id', 'started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_graph_sync_runs_hospital_started', table_name='graph_sync_runs')
    op.drop_index(op.f('ix_graph_sync_runs_hospital_id'), table_name='graph_sync_runs')
    op.drop_table('graph_sync_runs')
    # ### end Alembic commands ###
