"""v4 supplier intelligence: supplier orders and deliveries

Revision ID: edd9c4eaa152
Revises: 62cc820f507c
Create Date: 2026-09-23 09:01:27.781754
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'edd9c4eaa152'
down_revision: str | None = '62cc820f507c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('ordered_date', sa.Date(), nullable=False),
    sa.Column('quoted_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('expected_date', sa.Date(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('first_delivery_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('cancelled_date', sa.Date(), nullable=True),
    sa.Column('close_reason', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_supplier_orders_consumable_id_consumables')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_supplier_orders_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_supplier_orders_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_supplier_orders_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_orders')),
    sa.UniqueConstraint('hospital_id', 'reference', name='uq_supplier_orders_hospital_reference')
    )
    op.create_index(op.f('ix_supplier_orders_hospital_id'), 'supplier_orders', ['hospital_id'], unique=False)
    op.create_index('ix_supplier_orders_hospital_status', 'supplier_orders', ['hospital_id', 'status'], unique=False)
    op.create_index('ix_supplier_orders_supplier_item', 'supplier_orders', ['supplier_id', 'consumable_id'], unique=False)
    op.create_table('supplier_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_movement_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['stock_batches.id'], name=op.f('fk_supplier_deliveries_batch_id_stock_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_supplier_deliveries_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['supplier_orders.id'], name=op.f('fk_supplier_deliveries_order_id_supplier_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_movement_id'], ['stock_movements.id'], name=op.f('fk_supplier_deliveries_stock_movement_id_stock_movements'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplier_deliveries'))
    )
    op.create_index(op.f('ix_supplier_deliveries_hospital_id'), 'supplier_deliveries', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_supplier_deliveries_order_id'), 'supplier_deliveries', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_deliveries_order_id'), table_name='supplier_deliveries')
    op.drop_index(op.f('ix_supplier_deliveries_hospital_id'), table_name='supplier_deliveries')
    op.drop_table('supplier_deliveries')
    op.drop_index('ix_supplier_orders_supplier_item', table_name='supplier_orders')
    op.drop_index('ix_supplier_orders_hospital_status', table_name='supplier_orders')
    op.drop_index(op.f('ix_supplier_orders_hospital_id'), table_name='supplier_orders')
    op.drop_table('supplier_orders')
    # ### end Alembic commands ###
