"""v2 forecasting: model_versions, model_item_metrics, forecasts

Revision ID: 207788448e4f
Revises: 71315b2fc2a2
Create Date: 2026-09-23 06:12:10.786633
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '207788448e4f'
down_revision: str | None = '71315b2fc2a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trained_by_id', sa.Integer(), nullable=True),
    sa.Column('data_start', sa.Date(), nullable=False),
    sa.Column('data_end', sa.Date(), nullable=False),
    sa.Column('test_start', sa.Date(), nullable=False),
    sa.Column('test_end', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('n_series', sa.Integer(), nullable=False),
    sa.Column('n_train_rows', sa.Integer(), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_model_versions_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trained_by_id'], ['users.id'], name=op.f('fk_model_versions_trained_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_model_versions_hospital_name')
    )
    op.create_index(op.f('ix_model_versions_hospital_id'), 'model_versions', ['hospital_id'], unique=False)
    op.create_index('ix_model_versions_hospital_run', 'model_versions', ['hospital_id', 'run_id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('forecast_date', sa.Date(), nullable=False),
    sa.Column('horizon', sa.Integer(), nullable=False),
    sa.Column('predicted', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_forecasts_consumable_id_consumables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_forecasts_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_forecasts_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_forecasts')),
    sa.UniqueConstraint('model_version_id', 'consumable_id', 'forecast_date', name='uq_forecasts_model_item_date')
    )
    op.create_index('ix_forecasts_consumable_date', 'forecasts', ['consumable_id', 'forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_hospital_id'), 'forecasts', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_forecasts_model_version_id'), 'forecasts', ['model_version_id'], unique=False)
    op.create_table('model_item_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('actual_total', sa.Float(), nullable=False),
    sa.Column('predicted_total', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('wape', sa.Float(), nullable=True),
    sa.Column('bias', sa.Float(), nullable=True),
    sa.Column('residual_std', sa.Float(), nullable=False),
    sa.Column('n_points', sa.Integer(), nullable=False),
    sa.Column('daily', sa.JSON(), nullable=True),
    sa.Column('drivers', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_model_item_metrics_consumable_id_consumables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_model_item_metrics_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_item_metrics')),
    sa.UniqueConstraint('model_version_id', 'consumable_id', name='uq_model_item_metrics_model_item')
    )
    op.create_index(op.f('ix_model_item_metrics_consumable_id'), 'model_item_metrics', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_model_item_metrics_model_version_id'), 'model_item_metrics', ['model_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_item_metrics_model_version_id'), table_name='model_item_metrics')
    op.drop_index(op.f('ix_model_item_metrics_consumable_id'), table_name='model_item_metrics')
    op.drop_table('model_item_metrics')
    op.drop_index(op.f('ix_forecasts_model_version_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_hospital_id'), table_name='forecasts')
    op.drop_index('ix_forecasts_consumable_date', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('ix_model_versions_hospital_run', table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_hospital_id'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
