"""v5 procurement recommendations and settings

Revision ID: fe7e6ae943d8
Revises: edd9c4eaa152
Create Date: 2026-09-23 12:32:07.104512
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'fe7e6ae943d8'
down_revision: str | None = 'edd9c4eaa152'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procurement_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('service_level', sa.Float(), nullable=False),
    sa.Column('review_period_days', sa.Integer(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('stockout_cost_multiplier', sa.Float(), nullable=False),
    sa.Column('holding_cost_rate', sa.Float(), nullable=False),
    sa.Column('disposal_cost_pct', sa.Float(), nullable=False),
    sa.Column('order_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('allow_split', sa.Boolean(), nullable=False),
    sa.Column('budget_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('simulations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_procurement_settings_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_procurement_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_settings')),
    sa.UniqueConstraint('hospital_id', name=op.f('uq_procurement_settings_hospital_id'))
    )
    op.create_table('procurement_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('stockout_prediction_id', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('need_by_date', sa.Date(), nullable=True),
    sa.Column('order_by_date', sa.Date(), nullable=True),
    sa.Column('scenario_key', sa.String(length=64), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_breakdown', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('scenarios', sa.JSON(), nullable=False),
    sa.Column('replenishment', sa.JSON(), nullable=False),
    sa.Column('in_transit', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('settings_snapshot', sa.JSON(), nullable=False),
    sa.Column('solver', sa.JSON(), nullable=False),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('modified', sa.Boolean(), nullable=False),
    sa.Column('final_lines', sa.JSON(), nullable=True),
    sa.Column('final_evaluation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_procurement_recommendations_consumable_id_consumables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], name=op.f('fk_procurement_recommendations_decided_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_procurement_recommendations_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_procurement_recommendations_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stockout_prediction_id'], ['stockout_predictions.id'], name=op.f('fk_procurement_recommendations_stockout_prediction_id_stockout_predictions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procurement_recommendations'))
    )
    op.create_index(op.f('ix_procurement_recommendations_consumable_id'), 'procurement_recommendations', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_procurement_recommendations_hospital_id'), 'procurement_recommendations', ['hospital_id'], unique=False)
    op.create_index('ix_procurement_recommendations_hospital_status', 'procurement_recommendations', ['hospital_id', 'status'], unique=False)
    op.create_index(op.f('ix_procurement_recommendations_run_id'), 'procurement_recommendations', ['run_id'], unique=False)
    op.add_column('supplier_orders', sa.Column('recommendation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_supplier_orders_recommendation_id'), 'supplier_orders', ['recommendation_id'], unique=False)
    op.create_foreign_key(op.f('fk_supplier_orders_recommendation_id_procurement_recommendations'), 'supplier_orders', 'procurement_recommendations', ['recommendation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_supplier_orders_recommendation_id_procurement_recommendations'), 'supplier_orders', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_orders_recommendation_id'), table_name='supplier_orders')
    op.drop_column('supplier_orders', 'recommendation_id')
    op.drop_index(op.f('ix_procurement_recommendations_run_id'), table_name='procurement_recommendations')
    op.drop_index('ix_procurement_recommendations_hospital_status', table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_hospital_id'), table_name='procurement_recommendations')
    op.drop_index(op.f('ix_procurement_recommendations_consumable_id'), table_name='procurement_recommendations')
    op.drop_table('procurement_recommendations')
    op.drop_table('procurement_settings')
    # ### end Alembic commands ###
