"""v3 stockout risk: risk model versions, stockout predictions

Revision ID: 62cc820f507c
Revises: c67619e5a251
Create Date: 2026-09-23 07:47:17.742803
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '62cc820f507c'
down_revision: str | None = 'c67619e5a251'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trained_by_id', sa.Integer(), nullable=True),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('data_start', sa.Date(), nullable=False),
    sa.Column('data_end', sa.Date(), nullable=False),
    sa.Column('eval_start', sa.Date(), nullable=True),
    sa.Column('eval_end', sa.Date(), nullable=True),
    sa.Column('n_train_rows', sa.Integer(), nullable=False),
    sa.Column('n_positive_train', sa.Integer(), nullable=False),
    sa.Column('dataset_hash', sa.String(length=64), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('evaluation', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('warn_threshold', sa.Float(), nullable=False),
    sa.Column('high_threshold', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('artifact', sa.LargeBinary(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_risk_model_versions_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trained_by_id'], ['users.id'], name=op.f('fk_risk_model_versions_trained_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_model_versions'))
    )
    op.create_index('ix_risk_model_versions_hospital_active', 'risk_model_versions', ['hospital_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_risk_model_versions_hospital_id'), 'risk_model_versions', ['hospital_id'], unique=False)
    op.create_table('stockout_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('risk_model_version_id', sa.Integer(), nullable=True),
    sa.Column('forecast_model_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('usable_stock', sa.Integer(), nullable=False),
    sa.Column('forecast_7', sa.Float(), nullable=False),
    sa.Column('forecast_14', sa.Float(), nullable=False),
    sa.Column('forecast_30', sa.Float(), nullable=False),
    sa.Column('days_of_stock_remaining', sa.Integer(), nullable=True),
    sa.Column('expected_stockout_date', sa.Date(), nullable=True),
    sa.Column('shortage_quantity', sa.Integer(), nullable=False),
    sa.Column('expiring_quantity', sa.Integer(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('order_by_date', sa.Date(), nullable=True),
    sa.Column('can_replenish_in_time', sa.Boolean(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('probability_source', sa.String(length=32), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('drivers', sa.JSON(), nullable=True),
    sa.Column('projection', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_stockout_predictions_consumable_id_consumables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['forecast_model_version_id'], ['model_versions.id'], name=op.f('fk_stockout_predictions_forecast_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_stockout_predictions_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['risk_model_version_id'], ['risk_model_versions.id'], name=op.f('fk_stockout_predictions_risk_model_version_id_risk_model_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stockout_predictions'))
    )
    op.create_index('ix_stockout_predictions_hospital_created', 'stockout_predictions', ['hospital_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stockout_predictions_hospital_id'), 'stockout_predictions', ['hospital_id'], unique=False)
    op.create_index('ix_stockout_predictions_item_created', 'stockout_predictions', ['consumable_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stockout_predictions_item_created', table_name='stockout_predictions')
    op.drop_index(op.f('ix_stockout_predictions_hospital_id'), table_name='stockout_predictions')
    op.drop_index('ix_stockout_predictions_hospital_created', table_name='stockout_predictions')
    op.drop_table('stockout_predictions')
    op.drop_index(op.f('ix_risk_model_versions_hospital_id'), table_name='risk_model_versions')
    op.drop_index('ix_risk_model_versions_hospital_active', table_name='risk_model_versions')
    op.drop_table('risk_model_versions')
    # ### end Alembic commands ###
