"""v10 real hospital pilot and business validation: pilots (baseline + pilot periods, lifecycle, data classification),
participants, linked V9 data sources, pilot issues, feedback, recommendation views (decision funnel), readiness
confirmations, immutable report snapshots; PostgreSQL tenant-consistency triggers on the new hospital-owned tables.
Purely additive (no existing table changes).

Revision ID: b8c6b2c0cc67
Revises: 5684eca6bc5c
Create Date: 2026-09-24 11:52:19.467040
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'b8c6b2c0cc67'
down_revision: str | None = '5684eca6bc5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tenant-consistency trigger specs for the new tables (from app.db.tenant_guard.tenant_refs, frozen here).
TENANT_REFS = {'pilot_participants': (True, [('department_id', 'departments'), ('pilot_id', 'pilots')]), 'pilot_data_sources': (True, [('pilot_id', 'pilots'), ('source_id', 'integration_sources')]), 'pilot_issues': (True, [('pilot_id', 'pilots')]), 'pilot_feedback': (True, [('pilot_id', 'pilots'), ('recommendation_id', 'procurement_recommendations')]), 'recommendation_views': (True, [('recommendation_id', 'procurement_recommendations')]), 'pilot_readiness': (True, [('pilot_id', 'pilots')]), 'pilot_report_snapshots': (True, [('pilot_id', 'pilots')])}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pilots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_classification', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('baseline_start', sa.Date(), nullable=False),
    sa.Column('baseline_end', sa.Date(), nullable=False),
    sa.Column('pilot_start', sa.Date(), nullable=False),
    sa.Column('pilot_end', sa.Date(), nullable=False),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_factors', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('baseline_end < pilot_start', name=op.f('ck_pilots_baseline_before_pilot')),
    sa.CheckConstraint('baseline_start <= baseline_end', name=op.f('ck_pilots_baseline_order')),
    sa.CheckConstraint('pilot_start <= pilot_end', name=op.f('ck_pilots_pilot_order')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_pilots_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilots_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_pilots_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_pilots_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilots')),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_pilots_hospital_name')
    )
    op.create_index(op.f('ix_pilots_hospital_id'), 'pilots', ['hospital_id'], unique=False)
    op.create_index('ix_pilots_hospital_status', 'pilots', ['hospital_id', 'status'], unique=False)
    op.create_index(op.f('ix_pilots_organization_id'), 'pilots', ['organization_id'], unique=False)
    op.create_table('pilot_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilot_data_sources_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name=op.f('fk_pilot_data_sources_pilot_id_pilots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_pilot_data_sources_source_id_integration_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_data_sources')),
    sa.UniqueConstraint('pilot_id', 'source_id', name='uq_pilot_data_sources')
    )
    op.create_index(op.f('ix_pilot_data_sources_hospital_id'), 'pilot_data_sources', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_pilot_data_sources_pilot_id'), 'pilot_data_sources', ['pilot_id'], unique=False)
    op.create_table('pilot_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_pilot_issues_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_pilot_issues_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilot_issues_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name=op.f('fk_pilot_issues_pilot_id_pilots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_pilot_issues_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_issues'))
    )
    op.create_index(op.f('ix_pilot_issues_hospital_id'), 'pilot_issues', ['hospital_id'], unique=False)
    op.create_index('ix_pilot_issues_pilot_status', 'pilot_issues', ['pilot_id', 'status'], unique=False)
    op.create_table('pilot_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('(department_id IS NULL) <> (user_id IS NULL)', name=op.f('ck_pilot_participants_one_kind')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_pilot_participants_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilot_participants_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name=op.f('fk_pilot_participants_pilot_id_pilots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pilot_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_participants')),
    sa.UniqueConstraint('pilot_id', 'department_id', 'user_id', name='uq_pilot_participants')
    )
    op.create_index(op.f('ix_pilot_participants_hospital_id'), 'pilot_participants', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_pilot_participants_pilot_id'), 'pilot_participants', ['pilot_id'], unique=False)
    op.create_table('pilot_readiness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=48), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], name=op.f('fk_pilot_readiness_confirmed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilot_readiness_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name=op.f('fk_pilot_readiness_pilot_id_pilots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_readiness')),
    sa.UniqueConstraint('pilot_id', 'item_key', name='uq_pilot_readiness_item')
    )
    op.create_index(op.f('ix_pilot_readiness_hospital_id'), 'pilot_readiness', ['hospital_id'], unique=False)
    op.create_table('pilot_report_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by_id', sa.Integer(), nullable=True),
    sa.Column('data_classification', sa.String(length=16), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_pilot_report_snapshots_generated_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilot_report_snapshots_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name=op.f('fk_pilot_report_snapshots_pilot_id_pilots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_report_snapshots'))
    )
    op.create_index(op.f('ix_pilot_report_snapshots_hospital_id'), 'pilot_report_snapshots', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_pilot_report_snapshots_pilot_id'), 'pilot_report_snapshots', ['pilot_id'], unique=False)
    op.create_table('pilot_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.String(length=16), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_pilot_feedback_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], name=op.f('fk_pilot_feedback_pilot_id_pilots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['procurement_recommendations.id'], name=op.f('fk_pilot_feedback_recommendation_id_procurement_recommendations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pilot_feedback_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pilot_feedback'))
    )
    op.create_index(op.f('ix_pilot_feedback_hospital_id'), 'pilot_feedback', ['hospital_id'], unique=False)
    op.create_index('ix_pilot_feedback_pilot_created', 'pilot_feedback', ['pilot_id', 'created_at'], unique=False)
    op.create_table('recommendation_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_recommendation_views_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['procurement_recommendations.id'], name=op.f('fk_recommendation_views_recommendation_id_procurement_recommendations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recommendation_views_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_views'))
    )
    op.create_index(op.f('ix_recommendation_views_hospital_id'), 'recommendation_views', ['hospital_id'], unique=False)
    op.create_index('ix_recommendation_views_hospital_viewed', 'recommendation_views', ['hospital_id', 'viewed_at'], unique=False)
    op.create_index(op.f('ix_recommendation_views_recommendation_id'), 'recommendation_views', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        from app.db.tenant_guard import trigger_statements

        for stmt in trigger_statements(TENANT_REFS):
            op.get_bind().execute(sa.text(stmt))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_views_recommendation_id'), table_name='recommendation_views')
    op.drop_index('ix_recommendation_views_hospital_viewed', table_name='recommendation_views')
    op.drop_index(op.f('ix_recommendation_views_hospital_id'), table_name='recommendation_views')
    op.drop_table('recommendation_views')
    op.drop_index('ix_pilot_feedback_pilot_created', table_name='pilot_feedback')
    op.drop_index(op.f('ix_pilot_feedback_hospital_id'), table_name='pilot_feedback')
    op.drop_table('pilot_feedback')
    op.drop_index(op.f('ix_pilot_report_snapshots_pilot_id'), table_name='pilot_report_snapshots')
    op.drop_index(op.f('ix_pilot_report_snapshots_hospital_id'), table_name='pilot_report_snapshots')
    op.drop_table('pilot_report_snapshots')
    op.drop_index(op.f('ix_pilot_readiness_hospital_id'), table_name='pilot_readiness')
    op.drop_table('pilot_readiness')
    op.drop_index(op.f('ix_pilot_participants_pilot_id'), table_name='pilot_participants')
    op.drop_index(op.f('ix_pilot_participants_hospital_id'), table_name='pilot_participants')
    op.drop_table('pilot_participants')
    op.drop_index('ix_pilot_issues_pilot_status', table_name='pilot_issues')
    op.drop_index(op.f('ix_pilot_issues_hospital_id'), table_name='pilot_issues')
    op.drop_table('pilot_issues')
    op.drop_index(op.f('ix_pilot_data_sources_pilot_id'), table_name='pilot_data_sources')
    op.drop_index(op.f('ix_pilot_data_sources_hospital_id'), table_name='pilot_data_sources')
    op.drop_table('pilot_data_sources')
    op.drop_index(op.f('ix_pilots_organization_id'), table_name='pilots')
    op.drop_index('ix_pilots_hospital_status', table_name='pilots')
    op.drop_index(op.f('ix_pilots_hospital_id'), table_name='pilots')
    op.drop_table('pilots')
    # ### end Alembic commands ###
