"""v9 integrations and data exchange: integration sources, hashed inbound API keys, field mappings, sync runs,
rejected records, external references (idempotency), sync checkpoints, reconciliation issues; PostgreSQL
tenant-consistency triggers on the new hospital-owned tables. Purely additive (no existing table changes).

Revision ID: 5684eca6bc5c
Revises: 623279e318d6
Create Date: 2026-09-24 08:48:36.490463
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '5684eca6bc5c'
down_revision: str | None = '623279e318d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Tenant-consistency trigger specs for the new tables (from app.db.tenant_guard.tenant_refs, frozen here).
TENANT_REFS = {'integration_credentials': (True, [('source_id', 'integration_sources')]), 'integration_mappings': (True, [('source_id', 'integration_sources')]), 'sync_runs': (True, [('parent_run_id', 'sync_runs'), ('source_id', 'integration_sources')]), 'sync_records': (True, [('retried_in_run_id', 'sync_runs'), ('run_id', 'sync_runs')]), 'external_refs': (True, [('first_run_id', 'sync_runs'), ('last_run_id', 'sync_runs'), ('source_id', 'integration_sources')]), 'sync_checkpoints': (True, [('run_id', 'sync_runs'), ('source_id', 'integration_sources')]), 'reconciliation_issues': (True, [('consumable_id', 'consumables'), ('run_id', 'sync_runs'), ('source_id', 'integration_sources')])}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('system_type', sa.String(length=32), nullable=False),
    sa.Column('connector', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('service_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_integration_sources_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_integration_sources_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_user_id'], ['users.id'], name=op.f('fk_integration_sources_service_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_sources')),
    sa.UniqueConstraint('hospital_id', 'name', name='uq_integration_sources_hospital_name')
    )
    op.create_index(op.f('ix_integration_sources_hospital_id'), 'integration_sources', ['hospital_id'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_integration_credentials_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_integration_credentials_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_integration_credentials_source_id_integration_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_credentials')),
    sa.UniqueConstraint('key_prefix', name=op.f('uq_integration_credentials_key_prefix'))
    )
    op.create_index(op.f('ix_integration_credentials_hospital_id'), 'integration_credentials', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_integration_credentials_source_id'), 'integration_credentials', ['source_id'], unique=False)
    op.create_table('integration_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('field_map', sa.JSON(), nullable=False),
    sa.Column('defaults', sa.JSON(), nullable=False),
    sa.Column('date_format', sa.String(length=32), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_integration_mappings_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_integration_mappings_source_id_integration_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_integration_mappings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_mappings')),
    sa.UniqueConstraint('source_id', 'entity', name='uq_integration_mappings_source_entity')
    )
    op.create_index(op.f('ix_integration_mappings_hospital_id'), 'integration_mappings', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_integration_mappings_source_id'), 'integration_mappings', ['source_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('records_received', sa.Integer(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=True),
    sa.Column('checkpoint_before', sa.String(length=64), nullable=True),
    sa.Column('checkpoint_after', sa.String(length=64), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_sha256', sa.String(length=64), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_sync_runs_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['sync_runs.id'], name=op.f('fk_sync_runs_parent_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_sync_runs_source_id_integration_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], name=op.f('fk_sync_runs_triggered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_hospital_id'), 'sync_runs', ['hospital_id'], unique=False)
    op.create_index('ix_sync_runs_source_started', 'sync_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('external_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('first_run_id', sa.Integer(), nullable=True),
    sa.Column('last_run_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['first_run_id'], ['sync_runs.id'], name=op.f('fk_external_refs_first_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_external_refs_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_run_id'], ['sync_runs.id'], name=op.f('fk_external_refs_last_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_external_refs_source_id_integration_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_refs')),
    sa.UniqueConstraint('source_id', 'entity', 'external_id', name='uq_external_refs_source_entity_ext')
    )
    op.create_index(op.f('ix_external_refs_hospital_id'), 'external_refs', ['hospital_id'], unique=False)
    op.create_table('reconciliation_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('external_quantity', sa.Integer(), nullable=False),
    sa.Column('medflow_quantity', sa.Integer(), nullable=False),
    sa.Column('difference', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolution', sa.String(length=24), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_reconciliation_issues_consumable_id_consumables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_reconciliation_issues_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_reconciliation_issues_resolved_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['sync_runs.id'], name=op.f('fk_reconciliation_issues_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_reconciliation_issues_source_id_integration_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reconciliation_issues'))
    )
    op.create_index(op.f('ix_reconciliation_issues_hospital_id'), 'reconciliation_issues', ['hospital_id'], unique=False)
    op.create_index('ix_reconciliation_issues_hospital_status', 'reconciliation_issues', ['hospital_id', 'status'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=32), nullable=False),
    sa.Column('cursor', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_sync_checkpoints_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['sync_runs.id'], name=op.f('fk_sync_checkpoints_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['integration_sources.id'], name=op.f('fk_sync_checkpoints_source_id_integration_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_checkpoints')),
    sa.UniqueConstraint('source_id', 'entity', name='uq_sync_checkpoints_source_entity')
    )
    op.create_index(op.f('ix_sync_checkpoints_hospital_id'), 'sync_checkpoints', ['hospital_id'], unique=False)
    op.create_table('sync_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retried_in_run_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_sync_records_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retried_in_run_id'], ['sync_runs.id'], name=op.f('fk_sync_records_retried_in_run_id_sync_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['sync_runs.id'], name=op.f('fk_sync_records_run_id_sync_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_records'))
    )
    op.create_index(op.f('ix_sync_records_hospital_id'), 'sync_records', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_sync_records_run_id'), 'sync_records', ['run_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        from app.db.tenant_guard import trigger_statements

        for stmt in trigger_statements(TENANT_REFS):
            op.get_bind().execute(sa.text(stmt))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_records_run_id'), table_name='sync_records')
    op.drop_index(op.f('ix_sync_records_hospital_id'), table_name='sync_records')
    op.drop_table('sync_records')
    op.drop_index(op.f('ix_sync_checkpoints_hospital_id'), table_name='sync_checkpoints')
    op.drop_table('sync_checkpoints')
    op.drop_index('ix_reconciliation_issues_hospital_status', table_name='reconciliation_issues')
    op.drop_index(op.f('ix_reconciliation_issues_hospital_id'), table_name='reconciliation_issues')
    op.drop_table('reconciliation_issues')
    op.drop_index(op.f('ix_external_refs_hospital_id'), table_name='external_refs')
    op.drop_table('external_refs')
    op.drop_index('ix_sync_runs_source_started', table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_hospital_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_integration_mappings_source_id'), table_name='integration_mappings')
    op.drop_index(op.f('ix_integration_mappings_hospital_id'), table_name='integration_mappings')
    op.drop_table('integration_mappings')
    op.drop_index(op.f('ix_integration_credentials_source_id'), table_name='integration_credentials')
    op.drop_index(op.f('ix_integration_credentials_hospital_id'), table_name='integration_credentials')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_integration_sources_hospital_id'), table_name='integration_sources')
    op.drop_table('integration_sources')
    # ### end Alembic commands ###
