"""v2b procedure-aware forecasting: procedure types, schedules, item mappings

Revision ID: c67619e5a251
Revises: 207788448e4f
Create Date: 2026-09-23 06:45:41.867380
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c67619e5a251'
down_revision: str | None = '207788448e4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedure_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avg_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_procedure_types_department_id_departments')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_procedure_types_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedure_types')),
    sa.UniqueConstraint('hospital_id', 'code', name='uq_procedure_types_hospital_code')
    )
    op.create_index(op.f('ix_procedure_types_department_id'), 'procedure_types', ['department_id'], unique=False)
    op.create_index(op.f('ix_procedure_types_hospital_id'), 'procedure_types', ['hospital_id'], unique=False)
    op.create_table('procedure_item_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('procedure_type_id', sa.Integer(), nullable=False),
    sa.Column('consumable_id', sa.Integer(), nullable=False),
    sa.Column('quantity_per_procedure', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['consumable_id'], ['consumables.id'], name=op.f('fk_procedure_item_mappings_consumable_id_consumables'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_procedure_item_mappings_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_type_id'], ['procedure_types.id'], name=op.f('fk_procedure_item_mappings_procedure_type_id_procedure_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedure_item_mappings')),
    sa.UniqueConstraint('procedure_type_id', 'consumable_id', name='uq_procedure_item_mappings_type_item')
    )
    op.create_index(op.f('ix_procedure_item_mappings_consumable_id'), 'procedure_item_mappings', ['consumable_id'], unique=False)
    op.create_index(op.f('ix_procedure_item_mappings_hospital_id'), 'procedure_item_mappings', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_procedure_item_mappings_procedure_type_id'), 'procedure_item_mappings', ['procedure_type_id'], unique=False)
    op.create_table('procedure_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('procedure_type_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_procedure_schedules_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_procedure_schedules_department_id_departments')),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], name=op.f('fk_procedure_schedules_hospital_id_hospitals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['procedure_type_id'], ['procedure_types.id'], name=op.f('fk_procedure_schedules_procedure_type_id_procedure_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_procedure_schedules'))
    )
    op.create_index(op.f('ix_procedure_schedules_department_id'), 'procedure_schedules', ['department_id'], unique=False)
    op.create_index('ix_procedure_schedules_hospital_date', 'procedure_schedules', ['hospital_id', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_procedure_schedules_procedure_type_id'), 'procedure_schedules', ['procedure_type_id'], unique=False)
    op.create_index('uq_procedure_schedules_active_slot', 'procedure_schedules', ['procedure_type_id', 'department_id', 'scheduled_date'], unique=True, postgresql_where=sa.text("status <> 'CANCELLED'"), sqlite_where=sa.text("status <> 'CANCELLED'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_procedure_schedules_active_slot', table_name='procedure_schedules', postgresql_where=sa.text("status <> 'CANCELLED'"), sqlite_where=sa.text("status <> 'CANCELLED'"))
    op.drop_index(op.f('ix_procedure_schedules_procedure_type_id'), table_name='procedure_schedules')
    op.drop_index('ix_procedure_schedules_hospital_date', table_name='procedure_schedules')
    op.drop_index(op.f('ix_procedure_schedules_department_id'), table_name='procedure_schedules')
    op.drop_table('procedure_schedules')
    op.drop_index(op.f('ix_procedure_item_mappings_procedure_type_id'), table_name='procedure_item_mappings')
    op.drop_index(op.f('ix_procedure_item_mappings_hospital_id'), table_name='procedure_item_mappings')
    op.drop_index(op.f('ix_procedure_item_mappings_consumable_id'), table_name='procedure_item_mappings')
    op.drop_table('procedure_item_mappings')
    op.drop_index(op.f('ix_procedure_types_hospital_id'), table_name='procedure_types')
    op.drop_index(op.f('ix_procedure_types_department_id'), table_name='procedure_types')
    op.drop_table('procedure_types')
    # ### end Alembic commands ###
