"""V10 — pilot report (structured + Markdown). Built only from computed metrics; the conclusion is a list of measured,
neutrally worded facts. Demo-hospital pilots are labelled DEMO / SYNTHETIC DATA and never produce an outcome claim."""

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.db.base import utcnow
from app.models import Department, Hospital, Pilot, PilotIssue, PilotParticipant, User
from app.pilots import comparison, metrics
from app.pilots.readiness import evaluate as readiness

SECTIONS = [("data_quality", "2. Data quality"), ("inventory", "3. Inventory results"), ("forecasting", "4. Forecasting results"),
            ("stockouts", "5a. Stockout results"), ("stockout_prediction", "5b. Stockout prediction performance"),
            ("supplier", "6. Supplier results"), ("procurement", "7. Procurement results"), ("adoption", "8. User adoption")]
SYNTHETIC_BANNER = "DEMO / SYNTHETIC DATA — NOT REAL HOSPITAL DATA"
NO_CLAIM = "No real-world outcome claim can be made yet."


def fmt(v, unit: str) -> str:
    if v is None:
        return "—"
    if unit == "pct":
        return f"{v * 100:.1f}%"
    if unit == "money":
        return f"₹{v:,.0f}"
    if unit in ("days", "hours"):
        return f"{v:.1f} {unit}"
    if isinstance(v, float) and not v.is_integer():
        return f"{v:,.1f}"
    return f"{int(v):,}"


def fmt_diff(r: dict) -> str:
    if r["status"] != "ok":
        return "Insufficient data"
    parts = []
    if r["difference_pp"] is not None:
        parts.append(f"{r['difference_pp']:+.1f} pp")
    elif r["difference"] is not None:
        d = r["difference"]
        if r["unit"] == "money":
            parts.append(f"{'+' if d >= 0 else '−'}₹{abs(d):,.0f}")
        else:
            parts.append(f"{d:+,.1f}" if isinstance(d, float) and not float(d).is_integer() else f"{d:+,.0f}")
    if r["relative_change"] is not None:
        parts.append(f"{r['relative_change'] * 100:+.1f}% relative")
    return ", ".join(parts) or "0"


def build(db: Session, p: Pilot, user: User | None = None) -> dict:
    per = metrics.periods(p)
    base, pil = metrics.compute(db, p, per["baseline"]), metrics.compute(db, p, per["pilot"])
    rows = comparison.compare(base, pil, per["baseline"], per["pilot"])
    h = db.get(Hospital, p.hospital_id)
    synthetic = p.data_classification == "synthetic"
    depts = list(db.scalars(select(Department.name).join(PilotParticipant, PilotParticipant.department_id == Department.id)
                            .where(PilotParticipant.pilot_id == p.id).order_by(Department.name)))
    all_depts = list(db.scalars(select(Department.name).where(Department.hospital_id == p.hospital_id,
                                                               Department.is_active.is_(True)).order_by(Department.name)))
    n_users = len(list(db.scalars(select(PilotParticipant.id).where(PilotParticipant.pilot_id == p.id,
                                                                    PilotParticipant.user_id.is_not(None)))))
    sources = pil["integration_sources"]
    issues = list(db.scalars(select(PilotIssue).where(PilotIssue.pilot_id == p.id).order_by(PilotIssue.created_at)))
    models = next((m.get("models") for m in pil["metrics"] if m["key"] == "forecast_wape"), []) or []
    sections = []
    for key, title in SECTIONS:
        sections.append({"key": key, "title": title, "rows": [r for r in rows if r["section"] == key],
                         "pilot_only": [m for m in pil["metrics"] if m["section"] == key and m["key"] not in {r["key"] for r in rows}]})
    ok_rows = [r for r in rows if r["status"] == "ok"]
    insufficient = [r["label"] for r in rows if r["status"] != "ok"]
    dq = next((m for m in pil["metrics"] if m["key"] == "data_quality_pct"), None)
    limitations = []
    if synthetic:
        limitations.append(f"{SYNTHETIC_BANNER}. The demo hospital's data are generated by MedFlow's simulator and the "
                           "linked ERP is the local reference simulator; every number here is a synthetic/demo result.")
    more = "…" if len(insufficient) > 12 else ""
    limitations.append(f"Sample size: {len(ok_rows)} of {len(rows)} compared metrics had enough data in both periods"
                       + (f"; insufficient: {', '.join(insufficient[:12])}{more}." if insufficient else "."))
    limitations.append(f"Duration: baseline {per['baseline'].days} days, pilot {per['pilot'].days} days"
                       + (" (pilot still running — provisional)." if pil["period"]["partial"] else "."))
    if dq is not None:
        limitations.append("Data quality: " + (f"{fmt(dq['value'], 'pct')} of received records accepted on first attempt."
                                               if dq["sufficient"] else "too few integration records to assess."))
    if not sources:
        limitations.append("Missing systems: no V9 data source is linked, so inventory accuracy and data quality cannot be measured.")
    elif any(s["failed_runs"] for s in sources):
        limitations.append("Integration failures occurred: " + ", ".join(f"{s['name']} ({s['failed_runs']} failed runs)"
                                                                           for s in sources if s["failed_runs"]) + ".")
    missing = sorted(set(all_depts) - set(depts))
    if missing:
        limitations.append(f"Departments not participating: {', '.join(missing)} (their activity is still in hospital-wide metrics).")
    if p.external_factors:
        limitations.append("External factors recorded: " + "; ".join(f"{f['factor'].replace('_', ' ')} ({f['period']}): {f['note']}"
                                                                    for f in p.external_factors) + ".")
    limitations.append("Most metrics are hospital-wide (all items and departments), not limited to participants.")
    limitations.append(comparison.CAUSALITY)
    conclusion = []
    if synthetic:
        conclusion.append(f"{NO_CLAIM} This pilot ran on DEMO / SYNTHETIC DATA in a demo hospital; the numbers show that "
                          "the measurement workflow works, not how MedFlow performs in a real hospital.")
    elif pil["period"]["partial"]:
        conclusion.append("The pilot is still running; the results below are provisional.")
    if not ok_rows:
        conclusion.append("No metric had enough data in both periods, so no before/after statement can be made."
                          + ("" if synthetic else f" {NO_CLAIM}"))
    else:
        label = "Synthetic/demo result" if synthetic else "Observed pilot result"
        conclusion.append(f"{label}s (descriptive, not causal) — {len(ok_rows)} metric(s) with enough data in both periods:")
        for r in ok_rows[:10]:
            conclusion.append(f"{r['label']}: {fmt(r['baseline'], r['unit'])} (baseline) → {fmt(r['pilot'], r['unit'])} (pilot); "
                              f"{fmt_diff(r)}" + (f", {r['normalized']}" if r["normalized"] else "") + ".")
    conclusion.append(comparison.CAUSALITY)
    return {
        "title": f"MedFlow pilot report — {p.name}", "generated_at": utcnow(), "generated_by": user.full_name if user else None,
        "classification": p.data_classification, "banner": SYNTHETIC_BANNER if synthetic else None,
        "result_label": "Synthetic/demo result" if synthetic else "Observed pilot result",
        "comparison_label": comparison.LABEL, "causality_statement": comparison.CAUSALITY,
        "overview": {"hospital": h.name, "hospital_is_demo": h.is_demo, "pilot": p.name, "status": p.status,
                     "description": p.description,
                     "baseline": {"start": p.baseline_start, "end": p.baseline_end, "days": per["baseline"].days},
                     "pilot_period": {"start": p.pilot_start, "end": p.pilot_end, "actual_end": p.actual_end,
                                      "days": per["pilot"].days, "partial": pil["period"]["partial"]},
                     "departments": depts, "participating_users": n_users,
                     "data_sources": [{"name": s["name"], "connector": s["connector"], "simulated": s["is_simulated"]} for s in sources]},
        "sections": sections, "forecast_models": models, "integration_reliability": sources,
        "issues": [{"id": i.id, "category": i.category, "severity": i.severity, "title": i.title, "status": i.status,
                    "impact": i.impact, "resolution": i.resolution} for i in issues],
        "external_factors": p.external_factors or [], "readiness": readiness(db, p), "limitations": limitations,
        "conclusion": conclusion,
    }


def markdown(r: dict) -> str:
    o = r["overview"]
    L = [f"# {r['title']}", ""]
    if r["banner"]:
        L += [f"> **{r['banner']}** — every number in this report is a *synthetic/demo result*. {NO_CLAIM}", ""]
    else:
        L += ["> Observed pilot results from the hospital's own data. Descriptive only — see Limitations.", ""]
    L += [f"Generated {r['generated_at']:%Y-%m-%d %H:%M} UTC" + (f" by {r['generated_by']}" if r["generated_by"] else ""), "",
          "## 1. Pilot overview", "",
          f"- Hospital: {o['hospital']}" + (" (demo hospital)" if o["hospital_is_demo"] else ""),
          f"- Pilot: {o['pilot']} — status **{o['status']}**",
          f"- Baseline: {o['baseline']['start']} → {o['baseline']['end']} ({o['baseline']['days']} days)",
          f"- Pilot period: {o['pilot_period']['start']} → {o['pilot_period']['end']} ({o['pilot_period']['days']} days)"
          + (" — still running" if o["pilot_period"]["partial"] else ""),
          f"- Participating departments: {', '.join(o['departments']) or 'none'}; participating users: {o['participating_users']}",
          "- Data sources: " + (", ".join(f"{s['name']} ({s['connector']}{', simulated' if s['simulated'] else ''})"
                                          for s in o["data_sources"]) or "none"), "",
          f"All tables: *{r['comparison_label']}*. Values marked “Insufficient data” did not meet the minimum sample.", ""]
    for s in r["sections"]:
        L += [f"## {s['title']}", ""]
        if s["rows"]:
            L += ["| Metric | Baseline | Pilot | Difference |", "|---|---:|---:|---:|"]
            for row in s["rows"]:
                b = fmt(row["baseline"], row["unit"]) if row["baseline"] is not None else "Insufficient data"
                pv = fmt(row["pilot"], row["unit"]) if row["pilot"] is not None else "Insufficient data"
                L.append(f"| {row['label']}{' (per 30 days)' if row['normalized'] else ''} | {b} | {pv} | {fmt_diff(row)} |")
            L.append("")
        for m in s["pilot_only"]:
            L.append(f"- {m['label']} (pilot): " + (fmt(m["value"], m["unit"]) if m["sufficient"] else "Insufficient data"))
        if s["key"] == "forecasting" and r["forecast_models"]:
            L += ["", "Served forecasting models (V2, unchanged): " + "; ".join(
                f"{m['name']} ({m['type']}, data to {m['data_end']}, holdout WAPE "
                f"{fmt(m['holdout_wape'], 'pct')})" for m in r["forecast_models"])]
        if s["key"] == "data_quality":
            L += ["", "Integration reliability (pilot period):", "",
                  "| Source | Runs | Failed | Records | Rejected | Avg duration | Freshness |", "|---|---:|---:|---:|---:|---:|---|"]
            for x in r["integration_reliability"]:
                fr = x["freshness"]
                L.append(f"| {x['name']}{' (simulated)' if x['is_simulated'] else ''} | {x['runs']} | {x['failed_runs']} | "
                         f"{x['records_processed']} | {x['records_rejected']} | "
                         f"{'—' if x['avg_duration_s'] is None else str(x['avg_duration_s']) + ' s'} | "
                         f"{'no data' if fr['age_hours'] is None else str(fr['age_hours']) + ' h'}{' (stale)' if fr['stale'] else ''} |")
        L.append("")
    L += ["## 9. Issues encountered", ""]
    if r["issues"]:
        L += ["| Issue | Category | Severity | Status | Impact | Resolution |", "|---|---|---|---|---|---|"]
        for i in r["issues"]:
            L.append(f"| {i['title']} | {i['category'].replace('_', ' ')} | {i['severity']} | {i['status']} | "
                     f"{i['impact'] or '—'} | {i['resolution'] or '—'} |")
    else:
        L.append("No issues were logged.")
    L += ["", "## 10. Limitations", ""] + [f"- {x}" for x in r["limitations"]]
    L += ["", "## 11. Conclusion", ""] + [f"- {x}" for x in r["conclusion"]]
    rd = r["readiness"]
    L += ["", f"Readiness checklist: {rd['done']} of {rd['total']} items done. {rd['statement']}", ""]
    return "\n".join(L)
